### ISSUE TITLE
release on F-droid

### ISSUE THREAD

**Issue by graingert** [javiersantos/WhatsAppBetaUpdater#10]
Can you apply to have this on F-droid?

**Comment by Seranok** [comment]
Possibly. I guess that could also enable him to have ads on the app again, moreover to push regular updates.

**Comment by javiersantos** [comment]
@graingert I have submitted the source to the queue. I will update this issue when I have a response from f-droid https://f-droid.org/forums/topic/beta-updater-for-whatsapp-2/

@Seranok I don't know if showing ads again is a good decision. It will be ad-free for now.

**Comment by javiersantos** [comment]
Beta Updater for WhatsApp has been included on F-Droid https://f-droid.org/repository/browse/?fdfilter=whatsapp&fdid=com.javiersantos.whatsappbetaupdater
