### ISSUE TITLE
Push-based implementation

### ISSUE THREAD

**Issue by MarcelGerber** [javiersantos/WhatsAppBetaUpdater#12]
This is more of a suggestion than a feature request.

In my opinion, polling for updates on a central server (every 5 minutes or so) and then sending push notifications out to clients makes more sense than having all clients poll the server themselves.

The server-side of this is quite easy to implement. Just setup a small server, make it poll the website (you can probably reuse the existing logic), and if the version has changed, send push notifications through Google Cloud Messaging.
The client-side is probably harder to do (I've never done app programing myself so I can't really judge), but I presume it's not that hard either.

**Comment by beli3ver** [comment]
Please don't do this
There a users Luke me they remove all Google apps from there Android phone 
So when you will usw GCM we are out.
I Luke how it works

**Comment by javiersantos** [comment]
In my opinion, this may be the most optimal way to implement notifications for a proprietary software. But in this case, switching to push notifications through Google Cloud Messaging would complicate any derivative work (it wouldn't only depend by the app itself).
