### ISSUE TITLE
Whatsapp Officially Launches Beta Program

### ISSUE THREAD

**Issue by Seranok** [javiersantos/WhatsAppBetaUpdater#28]
Apparently on whatsapp.com/android they show a hyperlink to opt for beta program. https://play.google.com/apps/testing/com.whatsapp/join
Moreover, you might want to request support for your app as I have noticed many Whatsapp Updaters in google play store. But I guess this beta program destroys all that.

**Comment by javiersantos** [comment]
It seems that the beta updates on Google Play take many hours to reach all the users. However they continue publishing beta updates on their website.

I updated the app yesterday to support this new beta updates. An example:

Latest beta on Google Play: .469
Latest beta on Beta Updater: .471

**Comment by Seranok** [comment]
So I guess it calls for alpha release?
