### ISSUE TITLE
cannot install version 3.14

### ISSUE THREAD

**Issue by msebald** [javiersantos/WhatsAppBetaUpdater#29]
When starting the app the version 3.14 is offered for download and installation. I do this but the installation terminates with the error "App wurde nicht installiert" (German for "app was not installed"), that's it, no further information visible.

**Comment by javiersantos** [comment]
The updater included in the app only works when Beta Updater has been installed using the official download from GitHub. If you have installed Beta Updater from another website where the apk has been signed with another key the updater won't work (i.e. F-Droid).
