### ISSUE TITLE
Version 3.1.4 not picked up by FDroid.

### ISSUE THREAD

**Issue by Bubu** [javiersantos/WhatsAppBetaUpdater#30]
Probably because the 3.1.4 git-tag doesn't include the manifest changes from here: f3e30a8a8092fcafa66addcf28d9d90d30de9d05

**Comment by javiersantos** [comment]
Update 3.1.5 available on F-Droid: https://f-droid.org/repository/browse/?fdid=com.javiersantos.whatsappbetaupdater
