### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [javiersantos/WhatsAppBetaUpdater#31]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file with the appropriate link to the page of your app on F-Droid.

**Comment by javiersantos** [comment]
I will include the button as soon as the latest update is published on F-Droid too #30 

Thanks!

**Comment by javiersantos** [comment]
Added :+1:
