### ISSUE TITLE
WhatsAppBetaUpdater just crashes when there's no internet connection

### ISSUE THREAD

**Issue by troubas** [javiersantos/WhatsAppBetaUpdater#41]
Hi,

I've just noticed that trying to open WhatsAppBetaUpdater without internet connection leads to an immediate crash.

**Comment by javiersantos** [comment]
Fixed in [latest update](https://github.com/javiersantos/WhatsAppBetaUpdater/releases/latest).

**Comment by ccpp** [comment]
I am not sure this is fixed. Since this week's update it crashes every time, also if there is internet! (Using fdroid's version 4.0)

**Comment by javiersantos** [comment]
The latest update is 4.0.1 and fixes some critical bugs from the previous version. You can download it from the [repository](https://github.com/javiersantos/WhatsAppBetaUpdater/releases/latest), but it won't take long to appear in F-Droid.
