### ISSUE TITLE
Problem With targetSdkVersion 22

### ISSUE THREAD

**Issue by alibrames** [javiersantos/WhatsAppBetaUpdater#47]
I get the error when i change  targetSdkVersion 22, i can't override 22 on  targetSdkVersion But Google are cracking down on any apps using below sdk 26 
Please can you help me to update targetSdkVersion   ??

**Comment by javiersantos** [comment]
Google Play doesn't allow to publish this app on the market, so there is no need to update the targetSdk at the moment.
