### ISSUE TITLE
Improvements and Suggestions For v3

### ISSUE THREAD

**Issue by Seranok** [javiersantos/WhatsAppBetaUpdater#9]
Hi, so I have got to know about v3 but however despite me not having a Google account, except one I forgot, I shall be putting me suggestions here if ye dont mind. =•}
* The app takes a lot of time to startup on my lenovo S60 running latest everything. After noting time, it nearly took 22 seconds to startup. You might want to reduce that.

* Create a counter list about how many people downloaded the update. Would be gud. Better detection of version can be done too. 

* Create an option in settings to automatically delete the apk after auto or manual download.

* Create an option in settings to add a time setter or something as to when the update should be installed as per device time.

* Don't know if you have heard of Google's latest pull down refresh button. You would if you used chrome on mobile or something. I think you can incorporate such a feature into this app.

That's it for now, will notify you if I find more ideas. I hope you implement most of the possible ones into this app.
When is the release date for v3?
Thanks.

**Comment by javiersantos** [comment]
Hi @Seranok, thanks for your suggestions. Nowadays I'm working on the upcoming 3.0 update.

* I have been reducing the time to startup. Update 3.0 will take less than 2 seconds to load the latest beta update.
* Pull To Refresh instead the refresh button.
* Root features (to be confirmed).

Right now there isn't a release date.

**Comment by Seranok** [comment]
Good job on v3. It is pretty good. Improvements I noticed are: 
#1 App startup is now immediate.
#2 You reduced app size by five times. 
Git job on the app. I have a few more suggestion, you may ignore it and close the issue if you like, they are 
#q Option in settings to automatically install the apk, deleate it and close the application when app is started. 
#q Autoupdate of beta version would be nice, I guess you could follow google play stores mdchanism of autoupdates of installed applications, however I dont know anything about that. 
Thanks and keep on developing.

**Comment by javiersantos** [comment]
Thanks @Seranok. I think both features could be implemented in the future, but it will require Root access for sure.

I am going to close the issue, but I will have this suggestion in mind for upcoming updates.
